### ISSUE TITLE
Can't be used behind an HTTP proxy

### ISSUE THREAD

**Issue by BinaryTweedDeej** [CloudCredo/cloudfocker#13]
The `fock this` step fails behind a corporate HTTP proxy. Setting an `https_proxy` environment variable sadly makes no difference. I've used `curl` to verify that the proxy setting is correct, so I'm guessing that the Go code doesn't respect the env var?

**Comment by hatofmonkeys** [comment]
Hi Dan. I hope life's treating you well. I'm deleting this repo pretty soon - it's being actively developed over at https://github.com/CloudCredo/cloudrocker . It's currently in a state of flux due to the shifting sands of Diego. If you'd like to pull request observing the proxy env var that would be awesome.
C

**Comment by BinaryTweedDeej** [comment]
Ta!
